### ISSUE TITLE
Ideas / To-do

### ISSUE THREAD

**Issue by jackdonofrio** [Jack1q/wake-me-up#2]
Ideas / to-do
- [x] Create web dashboard to change clock settings
- [x] #6
- [x] find hardware/speaker for playing non-buzzer audio
- [x] add button system: (Snooze, Loop through options)
- [x] Re-write readme
- [x] change name of data_collection to utils
- [ ] Add testing module 
- [x] add logger for debugging
- [ ] configure backlight to turn off at night
